#!/usr/bin/env python3
"""Build PortwayCore's Localizable.strings (en, fa) from the Android app's strings.xml files plus
the iOS-only tables in tools/strings/.

The keys are the Android resource names, so both apps say the same thing in the same words and a
translation fixed on one side can be carried to the other by re-running this. iOS tables win over
Android on a clash: that is how an Android sentence that names Android gets its iOS wording.

    tools/import_android_strings.py [path/to/wireguard-android/ui/src/main/res]

Android format specifiers are rewritten for Foundation: %s / %1$s -> %@ / %1$@. Plurals become
<name>_one and <name>_other.
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_RES = os.path.expanduser("~/dev/wireguard-app/wireguard-android/ui/src/main/res")
OUT = os.path.join(ROOT, "Packages/Portway/Sources/PortwayCore/Resources")
IOS = os.path.join(ROOT, "tools/strings")


def android_text(el):
    # Inner text including any inline markup, then Android's escapes.
    s = (el.text or "") + "".join(ET.tostring(c, encoding="unicode") for c in el)
    s = s.strip()
    if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
        s = s[1:-1]
    s = re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), s)
    s = s.replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n").replace("\\@", "@").replace("\\?", "?")
    s = re.sub(r"%(\d+\$)?s", lambda m: "%" + (m.group(1) or "") + "@", s)
    return s


def read_android(path):
    out = {}
    if not os.path.exists(path):
        return out
    for el in ET.parse(path).getroot():
        name = el.get("name")
        if el.tag == "string" and name:
            out[name] = android_text(el)
        elif el.tag == "plurals" and name:
            for item in el:
                q = item.get("quantity")
                if q in ("one", "other"):
                    out[f"{name}_{q}"] = android_text(item)
    return out


def read_strings(path):
    out = {}
    if not os.path.exists(path):
        return out
    text = open(path, encoding="utf-8").read()
    for m in re.finditer(r'^\s*"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;', text, re.M):
        out[m.group(1)] = m.group(2).encode("utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
    return out


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    res = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_RES
    for lang, android_dir in (("en", "values"), ("fa", "values-fa")):
        table = read_android(os.path.join(res, android_dir, "strings.xml"))
        for f in sorted(os.listdir(IOS)):
            if f.endswith(f".{lang}.strings"):
                table.update(read_strings(os.path.join(IOS, f)))
        os.makedirs(os.path.join(OUT, f"{lang}.lproj"), exist_ok=True)
        with open(os.path.join(OUT, f"{lang}.lproj", "Localizable.strings"), "w", encoding="utf-8") as fh:
            fh.write(f"/* Generated by tools/import_android_strings.py — do not edit; edit tools/strings/*.{lang}.strings or the Android strings.xml. */\n\n")
            for key in sorted(table):
                fh.write(f'"{escape(key)}" = "{escape(table[key])}";\n')
        print(f"{lang}: {len(table)} strings")
        # App Intents titles are read by Xcode at build time from the app's own bundle, so their
        # keys also go to a table compiled into the app and the widgets.
        intents = {k: v for k, v in table.items() if k.startswith(("intent_", "widget_"))}
        out_dir = os.path.join(ROOT, "Shared/Localization", f"{lang}.lproj")
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, "Intents.strings"), "w", encoding="utf-8") as fh:
            fh.write("/* Generated by tools/import_android_strings.py — do not edit. */\n\n")
            for key in sorted(intents):
                fh.write(f'"{escape(key)}" = "{escape(intents[key])}";\n')


if __name__ == "__main__":
    main()
